// src/lib/components/Fragebogen/StepWrapper.svelte
<!-- Picks the step for the current index and flow (Under50 or Over50). -->
<script lang="ts">
	import { getQuestionnaire } from "$lib/fragebogen/questionnaire.svelte";
	import StepZero from "./Steps/StepZero.svelte";
	import StepOne from "./Steps/StepOne.svelte";
	// Over50 Flow (51-800 & über 800 Immobilien)
	import StepTwoOver50 from "./Steps/Over50/StepTwoOver50.svelte";
	import StepThreeOver50 from "./Steps/Over50/StepThreeOver50.svelte";
	import StepFourOver50 from "./Steps/Over50/StepFourOver50.svelte";
	import StepFiveOver50 from "./Steps/Over50/StepFiveOver50.svelte";
	import StepSixOver50 from "./Steps/Over50/StepSixOver50.svelte";
	// Under50 Flow (1-50 Immobilien)
	import StepTwoUnder50 from "./Steps/Under50/StepTwoUnder50.svelte";
	import StepThreeUnder50 from "./Steps/Under50/StepThreeUnder50.svelte";
	import StepFourUnder50 from "./Steps/Under50/StepFourUnder50.svelte";

	const q = getQuestionnaire();

	const over50Steps = [
		StepTwoOver50,
		StepThreeOver50,
		StepFourOver50,
		StepFiveOver50,
		StepSixOver50,
	];
	// The Under50 flow reuses StepSixOver50 for the personal contact form
	const under50Steps = [
		StepTwoUnder50,
		StepThreeUnder50,
		StepFourUnder50,
		StepSixOver50,
	];

	// Steps 0 and 1 are the same in both flows. Skipping step 1 leaves no flow,
	// so nothing renders after it (as in Next).
	const Step = $derived.by(() => {
		if (q.step === 0) return StepZero;
		if (q.step === 1) return StepOne;
		if (q.isOver50) return over50Steps[q.step - 2];
		if (q.isUnder50) return under50Steps[q.step - 2];
		return undefined;
	});
</script>

{#key q.step}
	<Step />
{/key}

// src/components/Fragebogen/StepWrapper.tsx
import { QuestionareFormData } from "@/app/(service)/fragebogen/page";
import StepZero from "@/components/Fragebogen/Steps/StepZero";
import FragebogenStepOne from "@/components/Fragebogen/Steps/StepOne";
// Over50 Flow (51-800 & über 800 Immobilien)
import StepTwoOver50 from "@/components/Fragebogen/Steps/Over50/StepTwoOver50";
import StepThreeOver50 from "@/components/Fragebogen/Steps/Over50/StepThreeOver50";
import StepFourOver50 from "@/components/Fragebogen/Steps/Over50/StepFourOver50";
import StepFiveOver50 from "@/components/Fragebogen/Steps/Over50/StepFiveOver50";
import StepSixOver50 from "@/components/Fragebogen/Steps/Over50/StepSixOver50";
// Under50 Flow (1-50 Immobilien)
import StepTwoUnder50 from "@/components/Fragebogen/Steps/Under50/StepTwoUnder50";
import StepThreeUnder50 from "@/components/Fragebogen/Steps/Under50/StepThreeUnder50";
import StepFourUnder50 from "@/components/Fragebogen/Steps/Under50/StepFourUnder50";
import type {
	FieldErrors,
	UseFormRegister,
	UseFormSetValue,
	UseFormWatch,
} from "react-hook-form";

export type BaseStepProps = {
	register: UseFormRegister<QuestionareFormData>;
	watch: UseFormWatch<QuestionareFormData>;
	errors: FieldErrors<QuestionareFormData>;
	setValue: UseFormSetValue<QuestionareFormData>;
};

export type StepWrapperProps = BaseStepProps & {
	activeStep: number;
};

export default function StepWrapper({
	activeStep,
	register,
	watch,
	setValue,
	errors,
}: StepWrapperProps) {
	const propertyCategory = watch("property_count_category");
	// Over50 flow: 51-800 and über 800 Immobilien
	const isOver50Flow =
		propertyCategory === "51-800 Immobilien" ||
		propertyCategory === "über 800 Immobilien";
	// Under50 flow: 1-50 Immobilien
	const isUnder50Flow = propertyCategory === "1-50 Immobilien";

	const renderStep = () => {
		// Step 0 is always the same (Customer type)
		if (activeStep === 0) {
			return (
				<StepZero
					register={register}
					watch={watch}
					errors={errors}
					setValue={setValue}
					key="step-0"
				></StepZero>
			);
		}

		// Step 1 is always the same (property count selection)
		if (activeStep === 1) {
			return (
				<FragebogenStepOne
					register={register}
					watch={watch}
					errors={errors}
					setValue={setValue}
					key="step-1"
				/>
			);
		}

		// Over50 Flow: 51-800 and über 800 Immobilien
		if (isOver50Flow) {
			switch (activeStep) {
				case 2:
					return (
						<StepTwoOver50
							register={register}
							watch={watch}
							errors={errors}
							setValue={setValue}
							key="step-2-over50"
						/>
					);
				case 3:
					return (
						<StepThreeOver50
							register={register}
							watch={watch}
							errors={errors}
							setValue={setValue}
							key="step-3-over50"
						/>
					);
				case 4:
					return (
						<StepFourOver50
							register={register}
							watch={watch}
							errors={errors}
							setValue={setValue}
							key="step-4-over50"
						/>
					);
				case 5:
					return (
						<StepFiveOver50
							register={register}
							watch={watch}
							errors={errors}
							setValue={setValue}
							key="step-5-over50"
						/>
					);
				case 6:
					return (
						<StepSixOver50
							register={register}
							watch={watch}
							errors={errors}
							setValue={setValue}
							key="step-6-over50"
						/>
					);
				default:
					return null;
			}
		}

		// Under50 Flow: 1-50 Immobilien
		if (isUnder50Flow) {
			switch (activeStep) {
				case 2:
					return (
						<StepTwoUnder50
							register={register}
							watch={watch}
							errors={errors}
							setValue={setValue}
							key="step-2-under50"
						/>
					);
				case 3:
					return (
						<StepThreeUnder50
							register={register}
							watch={watch}
							errors={errors}
							setValue={setValue}
							key="step-3-under50"
						/>
					);
				case 4:
					return (
						<StepFourUnder50
							register={register}
							watch={watch}
							errors={errors}
							setValue={setValue}
							key="step-4-under50"
						/>
					);
				case 5:
					// Reuse StepSixOver50 for personal contact form
					return (
						<StepSixOver50
							register={register}
							watch={watch}
							errors={errors}
							setValue={setValue}
							key="step-5-under50-contact"
						/>
					);
				default:
					return null;
			}
		}

		// Fallback
		return null;
	};

	return renderStep();
}
