// src/lib/components/Basic/RichTextBlockImage/RichTextBlockImage.svelte
<script lang="ts">
	import type { RTImageNode } from "@prismicio/client";
	import type { RichTextComponentProps } from "@prismicio/svelte";
	import CmsImage from "$lib/components/Basic/Image/CmsImage.svelte";

	let { node }: RichTextComponentProps<RTImageNode> = $props();

	// GIFs are served as-is so they stay animated (next/image `unoptimized`).
	const isGif = $derived(
		!!node.url && new URL(node.url).pathname.toLowerCase().endsWith(".gif"),
	);
	const imageClass =
		"h-auto max-h-[400px] w-full max-w-full rounded-2xl object-cover shadow-lg";
</script>

{#if node.url}
	<div class="flex flex-col items-start justify-center gap-2.5">
		{#if isGif}
			<img
				src={node.url}
				alt={node.alt || ""}
				loading="lazy"
				decoding="async"
				class={imageClass}
			/>
		{:else}
			<CmsImage field={node} class={imageClass} />
		{/if}
		{#if node.alt}
			<span class="mx-auto block w-fit text-sm font-medium">{node.alt}</span>
		{/if}
	</div>
{/if}

// src/components/Basic/RichTextBlockImage/RichTextBlockImage.tsx
import { RTImageNode } from "@prismicio/client";
import Image from "next/image";

export default function RichTextBlockImage({ node }: { node: RTImageNode }) {
  if (!node.url) return null;

  const urlObj = new URL(node.url);
  const isGif = urlObj.pathname.toLowerCase().endsWith(".gif");
  return (
    <div className="flex flex-col items-start justify-center gap-2.5">
      <Image
        width={0}
        height={0}
        sizes="100vw"
        unoptimized={isGif}
        loading="lazy"
        src={node.url}
        alt={node.alt || ""}
        className="rounded-2xl object-cover shadow-lg max-w-full w-full max-h-[400px] h-auto"
      />
      {node.alt && (
        <span className="text-sm block mx-auto w-fit font-medium">
          {node.alt}
        </span>
      )}
    </div>
  );
}
