// src/lib/components/Common/ChatBot/AIChatInput.svelte
<script lang="ts">
	import { SendHorizontal, Square } from "@lucide/svelte";
	import { getChatContext } from "$lib/chat/context";

	const { ai } = getChatContext();
	let input = $state("");
	const busy = $derived(ai.status === "submitted" || ai.status === "streaming");
	// Next stayed disabled forever after an error; allow a retry
	const canType = $derived(ai.status === "ready" || ai.status === "error");

	function onsubmit(e: SubmitEvent) {
		e.preventDefault();
		if (input.trim()) {
			void ai.sendMessage({ text: input });
			input = "";
		}
	}
</script>

<form {onsubmit} class="flex w-full gap-2">
	<input
		bind:value={input}
		disabled={!canType}
		placeholder="Nachricht schreiben..."
		class="flex-1 rounded-full border border-gray-300 px-4 py-2 focus:ring-2 focus:ring-green-100 focus:outline-none disabled:opacity-50"
	/>

	{#if busy}
		<button
			title="Stop generation"
			type="button"
			onclick={() => ai.stop()}
			class="cursor-pointer rounded-full bg-white p-3 shadow-lg transition-colors hover:bg-gray-100"
		>
			<Square class="text-green-600" size={18} />
		</button>
	{:else}
		<button
			title="Send message"
			type="submit"
			disabled={!canType || !input.trim()}
			class="rounded-full bg-dark_green p-3 text-white shadow-lg transition-all hover:scale-105 disabled:cursor-not-allowed disabled:opacity-50"
		>
			<SendHorizontal size={18} />
		</button>
	{/if}
</form>

// src/components/Common/ChatBot/AIChatInput.tsx
import { ChatStatus } from 'ai';
import { SendHorizonal, Square } from 'lucide-react';
import React from 'react'

interface ChatInputProps {
  sendMessage: (message: { text: string }) => void;
  input: string;
  setInput: (input: string) => void;
  status: ChatStatus;
  stop: () => void;
}

export default function AIChatInput({ sendMessage, input, setInput, status, stop }: ChatInputProps) {
  return (
    <form
      onSubmit={(e) => {
        e.preventDefault();
        if (input.trim()) {
          sendMessage({ text: input });
          setInput("");
        }
      }}
      className="flex gap-2 w-full"
    >
      <input
        value={input}
        onChange={(e) => setInput(e.target.value)}
        disabled={status !== "ready"}
        placeholder="Nachricht schreiben..."
        className="flex-1 border border-gray-300 rounded-full px-4 py-2 focus:outline-none focus:ring-2 focus:ring-green-100 disabled:opacity-50"
      />

      {/* Send / Stop button */}
      {status === "submitted" || status === "streaming" ? (
        <button
          title="Stop generation"
          type="button"
          onClick={() => stop()}
          className="bg-white rounded-full p-3 shadow-lg hover:bg-gray-100 transition-colors cursor-pointer"
        >
          <Square className="text-green-600" size={18} />
        </button>
      ) : (
        <button
          title="Send message"
          type="submit"
          disabled={status !== "ready" || !input.trim()}
          className="bg-dark_green text-white rounded-full p-3 hover:scale-105 disabled:opacity-50 disabled:cursor-not-allowed transition-all shadow-lg"
        >
          <SendHorizonal size={18} />
        </button>
      )}
    </form>
  );
}
