// src/components/Swipers/FunctionsSwiper.tsx
"use client";

import { article1 } from "@/static/icons";
import Image from "next/image";
import React from "react";
import { Swiper, SwiperSlide } from "swiper/react";
import { Pagination, Autoplay } from "swiper/modules";
import type { FunctionsSlideType } from "@/types";
import { LazyLottie } from "@/components/Lottie/LazyLottie";

export const functionsSwiper: FunctionsSlideType[] = [
	{
		item: (
			<Image
				width={0}
				height={0}
				sizes="100vw"
				loading="lazy"
				className="large:w-full max-h-[244px] max-w-[300px] max-medium:max-h-full max-medium:w-full max-medium:max-w-full overflow-hidden max-large:object-fill"
				src={article1}
				alt="article image"
			/>
		),
		title: "Intelligente Messlösungen",
		subtitle:
			"Statten Sie Ihre Immobilie mit modernster Funktechnologie aus und erfassen Sie Warmwasser-, Kaltwasser- und Heizungsverbrauch sowie Rauchmelderdaten automatisch.",
	},
	{
		item: (
			<LazyLottie
				animationName="Animation_5"
				id="animation5function"
				wrapperClassName="relative max-h-[244px] max-w-[300px] max-medium:max-h-full max-medium:max-w-full overflow-hidden max-large:w-full max-large:object-fill"
			/>
		),
		title: "Verbrauchsdaten in Echtzeit",
		subtitle:
			"Behalten Sie Ihren Energieverbrauch stets im Blick. Unsere intelligente Technologie erfasst Verbrauchsdaten in Echtzeit und liefert wertvolle Insights –für eine effiziente Steuerung jederzeit und von überall.",
	},
	{
		item: (
			<LazyLottie
				animationName="Animation_6"
				id="animation6function"
				wrapperClassName="relative max-h-[244px] max-w-[300px] max-medium:max-h-full max-medium:max-w-full overflow-hidden max-large:w-full max-large:object-fill"
			/>
		),
		title: "Flexible Bedarfsanpassung",
		subtitle:
			"Wählen Sie mit nur einem Klick die passenden Messgeräte für Ihre Immobilie. Wir übernehmen die Installation und sorgen für eine reibungslose Integration.",
	},
	{
		item: (
			<LazyLottie
				animationName="Animation_4"
				id="animation4function"
				wrapperClassName="relative max-h-[244px] max-w-[300px] max-medium:max-h-full max-medium:max-w-full overflow-hidden max-large:w-full max-large:object-fill"
			/>
		),
		title: "Kundenservice 24/7",
		subtitle:
			"Unser Support ist rund um die Uhr für Sie da. Ob technische Fragen oder individuelle Anliegen –wir finden schnelle, kompetente Lösungen, genau dann, wenn Sie sie brauchen.",
	},
];

export default function FunctionsSwiper() {
	return (
		<div className="relative">
			{/* Swipe indicator - mobile only */}
			<div className="hidden max-medium:block absolute top-2 left-1/2 -translate-x-1/2 z-10 animate-fade-out">
				<div className="flex items-center gap-2 text-dark_text/60 text-sm animate-swipe-hint">
					<span>👆</span>
					<span>Wischen</span>
					<span className="animate-swipe-arrow">→</span>
				</div>
			</div>
			<Swiper
				modules={[Pagination, Autoplay]}
				spaceBetween={20}
				slidesPerView={1}
				pagination={{ clickable: true }}
				autoplay={{
					delay: 3000,
					disableOnInteraction: false,
					pauseOnMouseEnter: true,
				}}
				loop={true}
				className="swiper !pt-8 functions-swiper"
			>
				{functionsSwiper.map((slide, index) => (
					<SwiperSlide key={index} className="swiper-slide space-y-6">
						{slide.item}
						<p className="text-dark_text text-xl font-bold leading-[24px]">
							{slide.title}
						</p>
						<p className="text-dark_text leading-5 text-[17px]">
							{slide.subtitle}
						</p>
					</SwiperSlide>
				))}
			</Swiper>
		</div>
	);
}

// src/lib/components/Swipers/FunctionsSwiper.svelte
<script lang="ts">
	import { Autoplay, Pagination } from "swiper/modules";
	import Image from "$lib/components/Basic/Image/Image.svelte";
	import LazyLottie from "$lib/components/Lottie/LazyLottie.svelte";
	import { article1 } from "$lib/assets/icons";
	import { swiper } from "$lib/attachments/swiper";
	import {
		functionAnimations,
		functionLottieClass,
		functionTexts,
	} from "./functionSlides";
</script>

<div class="relative">
	<!-- Swipe indicator - mobile only -->
	<div
		class="animate-fade-out pointer-events-none absolute top-2 left-1/2 z-10 hidden -translate-x-1/2 max-medium:block"
	>
		<div
			class="animate-swipe-hint flex items-center gap-2 text-sm text-dark_text/60"
		>
			<span>👆</span>
			<span>Wischen</span>
			<span class="animate-swipe-arrow">→</span>
		</div>
	</div>
	<div
		class="swiper functions-swiper !pt-8"
		{@attach swiper({
			modules: [Pagination, Autoplay],
			spaceBetween: 20,
			slidesPerView: 1,
			pagination: { clickable: true },
			autoplay: {
				delay: 3000,
				disableOnInteraction: false,
				pauseOnMouseEnter: true,
			},
			loop: true,
		})}
	>
		<div class="swiper-wrapper">
			{#each functionTexts as slide, index (index)}
				<div class="swiper-slide space-y-6">
					{#if index === 0}
						<Image
							width={0}
							height={0}
							sizes="100vw"
							class="max-h-[244px] max-w-[300px] overflow-hidden max-large:object-fill max-medium:max-h-full max-medium:w-full max-medium:max-w-full large:w-full"
							src={article1}
							alt="article image"
						/>
					{:else}
						<LazyLottie
							animationName={functionAnimations[index - 1]}
							id="{functionAnimations[index - 1].replace(
								'Animation_',
								'animation',
							)}function"
							wrapperClassName={functionLottieClass}
						/>
					{/if}
					<p class="text-xl leading-[24px] font-bold text-dark_text">
						{slide.title}
					</p>
					<p class="text-[17px] leading-5 text-dark_text">
						{slide.subtitle}
					</p>
				</div>
			{/each}
		</div>
		<div class="swiper-pagination"></div>
	</div>
</div>
