// src/components/Header/LoginDropdown.tsx
"use client";

import Image from "next/image";
import { login } from "@/static/icons";

interface LoginDropdownProps {
  className?: string;
  isMobile?: boolean;
}

export default function LoginDropdown({ className = "", isMobile = false }: LoginDropdownProps) {

  if (isMobile) {
    return (
      <a
        href="https://platform.heidisystems.com/"
        target="_blank"
        rel="noopener noreferrer"
        className="w-full p-4 flex items-center gap-2 justify-center text-lg text-dark_text bg-white border-2 border-green rounded-halfbase min-h-12 hover:opacity-80 transition"
      >
        <Image
          width={20}
          height={20}
          loading="lazy"
          className="max-w-5 max-h-5"
          style={{ width: "100%", height: "auto" }}
          src={login}
          alt="login"
        />
        Einloggen
      </a>
    );
  }

  // Desktop version - direct link
  return (
    <a
      href="https://platform.heidisystems.com/"
      target="_blank"
      rel="noopener noreferrer"
      className={`p-2 flex items-center gap-1.5 justify-center text-base max-xl:text-sm text-dark_text hover:opacity-80 transition ${className}`}
    >
      <Image
        width={16}
        height={16}
        loading="lazy"
        className="max-w-4 max-h-4"
        style={{ width: "100%", height: "auto" }}
        src={login}
        alt="login"
      />
      Einloggen
    </a>
  );
}

// web/src/lib/components/Header/LoginDropdown.svelte
<script lang="ts">
	import Image from "$lib/components/Basic/Image/Image.svelte";
	import { login } from "$lib/assets/icons";

	let {
		class: className = "",
		isMobile = false,
	}: { class?: string; isMobile?: boolean } = $props();
</script>

{#if isMobile}
	<a
		href="https://platform.heidisystems.com/"
		target="_blank"
		rel="noopener noreferrer"
		class="flex min-h-12 w-full items-center justify-center gap-2 rounded-halfbase border-2 border-green bg-white p-4 text-lg text-dark_text transition hover:opacity-80"
	>
		<Image
			width={20}
			height={20}
			class="max-h-5 max-w-5"
			style="width: 100%; height: auto"
			src={login}
			alt="login"
		/>
		Einloggen
	</a>
{:else}
	<!-- Desktop version - direct link -->
	<a
		href="https://platform.heidisystems.com/"
		target="_blank"
		rel="noopener noreferrer"
		class="flex items-center justify-center gap-1.5 p-2 text-base text-dark_text transition hover:opacity-80 max-xl:text-sm {className}"
	>
		<Image
			width={16}
			height={16}
			class="max-h-4 max-w-4"
			style="width: 100%; height: auto"
			src={login}
			alt="login"
		/>
		Einloggen
	</a>
{/if}
