// src/routes/[[preview=preview]]/(base)/blog/[uid]/+page.svelte
<script lang="ts">
	import { SliceZone } from "@prismicio/svelte";
	import FAQSection from "$lib/components/Basic/FAQ/FAQSection.svelte";
	import Kostenfrei from "$lib/components/Basic/Kostenfrei/Kostenfrei.svelte";
	import RecommendedPosts from "$lib/components/Blog/RecommendedPosts.svelte";
	import type { BlogContext } from "$lib/server/blog";
	import { components } from "$lib/slices";

	let { data } = $props();

	const context: BlogContext = $derived({
		tags: data.post.tags,
		author: data.author,
	});
</script>

<svelte:head>
	<!-- Post images come straight from Prismic's CDN (Next proxied them through
	     /_next/image), so open that connection before the parser finds them. -->
	<link rel="preconnect" href="https://images.prismic.io" />
</svelte:head>

<!-- Next had id="content relative" (KI-13). -->
<main id="content" class="relative">
	<div class="px-20 max-medium:px-10 max-small:px-5">
		<div
			class="mx-auto mb-[52px] max-w-6xl space-y-7 pt-28 pb-4 max-large:pt-24 max-medium:pt-20 max-small:pt-28"
		>
			<SliceZone slices={data.post.data.slices} {components} {context} />
		</div>
		<RecommendedPosts posts={data.recommended} />
	</div>
	<FAQSection />
	<Kostenfrei />
</main>

// src/app/(base)/blog/[uid]/page.tsx
import FAQSection from "@/components/Basic/FAQ/FAQSection";
import Kostenfrei from "@/components/Basic/Kostenfrei/Kostenfrei";

import { Metadata } from "next";
import { notFound } from "next/navigation";
import { asImageSrc } from "@prismicio/client";
import { SliceZone } from "@prismicio/react";

import { createClient } from "@/prismicio";
import { components } from "@/slices";
import RecomendedBlogs from "@/components/Blog/RecomendedPosts";

type Params = { uid: string };

export default async function BlogPage({
  params,
}: {
  params: Promise<Params>;
}) {
  const uid = (await params).uid;
  const client = createClient();
  const page = await client.getByUID("blogpost", uid).catch(() => notFound());

  return (
    <main id="content relative">
      <div className="px-20 max-medium:px-10 max-small:px-5">
        <div className="max-w-6xl mx-auto pt-28 space-y-7 max-large:pt-24 max-medium:pt-20 max-small:pt-16 mb-[52px] pb-4">
          <SliceZone
            context={page}
            slices={page.data.slices}
            components={components}
          />
        </div>
        <RecomendedBlogs current={uid} />
      </div>
      <FAQSection />
      <Kostenfrei />
    </main>
  );
}

export async function generateMetadata({
  params,
}: {
  params: Promise<Params>;
}): Promise<Metadata> {
  const { uid } = await params;
  const client = createClient();

  const page = await client.getByUID("blogpost", uid).catch(() => notFound());

  return {
    title: "Heidi Systems",
    description: page.data.meta_description,
    openGraph: {
      images: [{ url: asImageSrc(page.data.meta_image) ?? "" }],
    },
  };
}
