// web/src/lib/components/Common/ChatBot/Messages/AiMessagesContainer.svelte
<script lang="ts">
	import { getChatContext } from "$lib/chat/context";
	import { scrollToBottom } from "$lib/attachments/scrollToBottom.svelte";
	import AIChatInput from "../AIChatInput.svelte";
	import AnonymousChatBanner from "../AnonymousChatBanner.svelte";
	import SupportAgentIcon from "../SupportAgentIcon.svelte";
	import DefaultChatMessage from "./DefaultChatMessage.svelte";
	import LoadingMessage from "./LoadingMessage.svelte";
	import Message from "./Message.svelte";

	const chat = getChatContext();
	const { ai } = chat;
	const busy = $derived(ai.status === "submitted" || ai.status === "streaming");
</script>

<div class="animate-from-right flex min-h-0 flex-1 flex-col">
	<div
		class="h-full max-h-full flex-1 overflow-scroll overflow-y-auto pb-4"
		{@attach scrollToBottom(() => [
			ai.messages.length,
			ai.messages.at(-1)?.parts.length,
			busy,
		])}
	>
		<div class="flex flex-col gap-3">
			{#if chat.isChatStarted && chat.anonymousUserEmail && !chat.isExistingClient}
				<AnonymousChatBanner />
			{/if}

			{#if ai.messages.length === 0}
				<DefaultChatMessage />
			{/if}

			{#each ai.messages as message (message.id)}
				<Message {message} />
			{/each}

			{#if busy}
				<LoadingMessage />
			{/if}
		</div>
	</div>

	<div
		class="flex w-full flex-col items-start justify-center gap-3 border-gray-200 pt-4"
	>
		<button
			title="Send message"
			onclick={chat.toggleChatType}
			class="cursor-pointer rounded-full bg-dark_green p-2 text-white shadow-lg transition-all hover:scale-105 disabled:cursor-not-allowed disabled:opacity-50"
		>
			<SupportAgentIcon size={30} class="text-white" />
		</button>

		<!-- Clear session button for anonymous users -->
		{#if !chat.isExistingClient && chat.isChatStarted}
			<div class="mb-2 flex w-full justify-end">
				<button
					onclick={chat.clearSessionEmail}
					class="text-xs text-gray-600 underline hover:text-red-600"
					title="Chat mit anderer E-Mail fortsetzen"
				>
					Andere E-Mail verwenden
				</button>
			</div>
		{/if}

		<AIChatInput />
	</div>
</div>

// src/components/Common/ChatBot/Messages/AiMessagesContainer.tsx
"use client";

import React, { Dispatch, useCallback, useEffect, useState } from "react";
import Message from "./Message";
import { ChatRequestOptions, ChatStatus, FileUIPart, UIDataTypes, UIMessage, UITools } from "ai";
import { SupportAgentIcon } from "../icons";
import { useAIMessagesStore } from "@/store/useAIMessagesStore";
import AIChatInput from "../AIChatInput";
import AnonymousChatBanner from "../AnonymousChatBanner";
import DefaultChatMessage from "./DefaultChatMessage";
import LoadingMessage from "./LoadingMessage";
import { SlackMessage } from "@/types/Chat";
interface AiMessagesContainerProps {
  isExistingClient: boolean;
  toggleChatType: () => void;
  aiMessages: UIMessage<unknown, UIDataTypes, UITools>[];
  sendMessage: (
    message?:
      | (Omit<UIMessage<unknown, UIDataTypes, UITools>, "id" | "role"> & {
          id?: string | undefined;
          role?: "user" | "system" | "assistant" | undefined;
        } & {
          text?: never;
          files?: never;
          messageId?: string;
        })
      | {
          text: string;
          files?: FileList | FileUIPart[];
          metadata?: unknown;
          parts?: never;
          messageId?: string;
        }
      | {
          files: FileList | FileUIPart[];
          metadata?: unknown;
          parts?: never;
          messageId?: string;
        }
      | undefined,
    options?: ChatRequestOptions
  ) => Promise<void>;
  status: ChatStatus;
  stop: () => Promise<void>;
  anonymousUserEmail: string;
  setAnonymousUserEmail: Dispatch<React.SetStateAction<string>>;
  isChatStarted: boolean;
  setIsChatStarted: Dispatch<React.SetStateAction<boolean>>;
}

export default function AiMessagesContainer({
  isExistingClient,
  toggleChatType,
  aiMessages,
  sendMessage,
  status,
  stop,
  anonymousUserEmail,
  setAnonymousUserEmail,
  isChatStarted,
  setIsChatStarted,
}: AiMessagesContainerProps) {
  const setStoredMessages = useAIMessagesStore(
    (state) => state.setStoredMessages
  );

  const [input, setInput] = useState("");

  useEffect(() => {
    setStoredMessages(aiMessages);
  }, [aiMessages, setStoredMessages]);

  const clearSessionEmail = () => {
    if (typeof window !== "undefined") {
      sessionStorage.removeItem("anonymousUserEmail");
      sessionStorage.removeItem("slack_thread_visitor");
      setAnonymousUserEmail("");
      setIsChatStarted(false);
    }
  };

  return (
    <div className="flex flex-col flex-1 min-h-0 animate-from-right">
      <div className="flex-1 overflow-y-auto pb-4 overflow-scroll max-h-full h-full">
        <div className="flex flex-col gap-3">
          {isChatStarted && anonymousUserEmail && !isExistingClient && (
            <AnonymousChatBanner
              anonymousUserEmail={anonymousUserEmail}
              clearSessionEmail={clearSessionEmail}
            />
          )}

          {aiMessages.length === 0 && (
            <DefaultChatMessage
              anonymousUserEmail={anonymousUserEmail}
              isChatStarted={isChatStarted}
            />
          )}

          {aiMessages.map((message) => {
            const isUser = message.role === "user";
            return (
              <Message key={message.id} message={message} isUser={isUser} />
            );
          })}

          {(status === "submitted" || status === "streaming") && (
            <LoadingMessage />
          )}
        </div>
      </div>

      <div className="flex flex-col items-start justify-center w-full gap-3 pt-4 border-gray-200">
        <button
          title="Send message"
          onClick={toggleChatType}
          className="bg-dark_green text-white rounded-full p-2 hover:scale-105 disabled:opacity-50 disabled:cursor-not-allowed transition-all shadow-lg cursor-pointer"
        >
          <SupportAgentIcon className="w-[30px] h-[30px] text-white" />
        </button>

        {/* Show clear session button for anonymous users */}
        {!isExistingClient && isChatStarted && (
          <div className="w-full flex justify-end mb-2">
            <button
              onClick={clearSessionEmail}
              className="text-xs text-gray-600 hover:text-red-600 underline"
              title="Chat mit anderer E-Mail fortsetzen"
            >
              Andere E-Mail verwenden
            </button>
          </div>
        )}

        <AIChatInput
          sendMessage={sendMessage}
          input={input}
          setInput={setInput}
          status={status}
          stop={stop}
        />
      </div>
    </div>
  );
}
