// web/src/lib/components/Common/ChatBot/Messages/SlackMessage.svelte
<script lang="ts">
	import type { SlackMessage } from "$lib/chat/types";
	import { getChatContext } from "$lib/chat/context";
	import ChatMarkdown from "../ChatMarkdown.svelte";
	import SupportAgentIcon from "../SupportAgentIcon.svelte";
	import TriangleSpinner from "../TriangleSpinner.svelte";
	import Avatar from "./Avatar.svelte";

	let { message }: { message: SlackMessage } = $props();
	const { slack } = getChatContext();
	// Messages sent from the website are posted by the bot
	const isUser = $derived(message.role === "assistant");
</script>

<div class={["flex w-full gap-2", isUser ? "justify-end" : "justify-start"]}>
	{#if !isUser}
		<div>
			{#if slack.isOutOfOffice}
				<SupportAgentIcon class="h-[30px] w-[30px] text-white" />
			{:else}
				<Avatar />
			{/if}
		</div>
	{/if}
	<div
		class={[
			"max-w-[85%] rounded-2xl px-4 py-2",
			isUser
				? "rounded-br-sm bg-dark_green text-white"
				: "rounded-bl-sm bg-white text-gray-700",
		]}
	>
		<ChatMarkdown md={message.text} />
	</div>
	{#if !message.id}
		<div class="flex flex-row items-center justify-center">
			<TriangleSpinner size={14} />
		</div>
	{/if}
</div>

// src/components/Common/ChatBot/Messages/SlackMessage.tsx
import { useSlackChat } from '@/hooks/useSlackChat';
import { max_chat_avatar } from '@/static/icons';
import { SlackMessage } from '@/types/Chat';
import Image from 'next/image';
import React from 'react'
import { Triangle } from 'react-loader-spinner';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { SupportAgentIcon } from "../icons";

interface SlackMessageContainerProps {
  message: SlackMessage;
  userId?:string
}

export default function SlackMessageContainer({
  message,
  userId,
}: SlackMessageContainerProps) {
  const {isOutOfOffice} = useSlackChat(userId);
  const isUser = message.role === "assistant";
  return (
    <div
      className={`flex ${
        isUser ? "justify-end" : "justify-start"
      } gap-2 w-full`}
    >
      {!isUser && (
        <div>
          {isOutOfOffice ?
            <SupportAgentIcon className="w-[30px] h-[30px] text-white" /> :
            <Image
              alt="chat avatar"
              src={max_chat_avatar.src}
              width={40}
              height={40}
              className="rounded-full"
            />
          }
        </div>
      )}
      <div
        className={`max-w-[85%] rounded-2xl px-4 py-2 ${
          isUser
            ? "bg-dark_green text-white rounded-br-sm"
            : "bg-white text-gray-700 rounded-bl-sm"
        }`}
      >
        <ReactMarkdown
          remarkPlugins={[remarkGfm]}
          components={{
            a: (props: any) => (
              <a
                {...props}
                target="_blank"
                rel="noopener noreferrer"
                className="text-blue-600 underline"
              />
            ),
            strong: (props: any) => <strong {...props} className="font-bold" />,
            ul: (props: any) => (
              <ul {...props} className="list-disc list-inside ml-4" />
            ),
            ol: (props: any) => (
              <ol {...props} className="list-decimal list-inside ml-4" />
            ),
            h1: (props: any) => (
              <h1 {...props} className="text-lg font-bold mt-3" />
            ),
            h2: (props: any) => (
              <h2 {...props} className="text-base font-bold mt-2" />
            ),
            h3: (props: any) => (
              <h3 {...props} className="text-sm font-bold mt-2" />
            ),
          }}
        >
          {message.text}
        </ReactMarkdown>
      </div>
      {!message.id && (
        <div className="flex flex-row items-center justify-center">
          <Triangle
            visible={true}
            height="14"
            width="14"
            color="#4fa94d"
            ariaLabel="triangle-loading"
            wrapperStyle={{}}
            wrapperClass=""
          />
        </div>
      )}
    </div>
  );
}
