// src/slices/BlogImage/index.tsx
import { FC, Fragment } from "react";
import { Content } from "@prismicio/client";
import { SliceComponentProps } from "@prismicio/react";
import Image from "next/image";
import { formatDate } from "@/utils";
import CopyLinkButton from "@/components/Basic/CopyLinkButton/CopyLinkButton";
import { AllDocumentTypes } from "../../../prismicio-types";

/**
 * Props for `BlogImage`.
 */
export type BlogImageProps = SliceComponentProps<
  Content.BlogImageSlice,
  AllDocumentTypes
>;

/**
 * Component for "BlogImage" Slices.
 */

const BlogImage: FC<BlogImageProps> = ({ slice, context }) => {
  return (
    <Fragment>
      <div className="flex items-center blogImage justify-between max-medium:grid max-medium:grid-cols-2 gap-2">
        <div className="flex items-center flex-wrap gap-1 blogImageTags">
          {context?.tags?.map((tag: string) => (
            <span
              key={tag}
              className="text-xs font-medium bg-green/30 rounded-full px-2 py-1 mr-2">
              {tag}
            </span>
          ))}
        </div>
        <span className="text-sm max-medium:text-base blogImageDate text-gray-500">
          {slice.primary.creationdate
            ? formatDate(slice.primary.creationdate)
            : ""}
        </span>
        <CopyLinkButton />
      </div>
      <section
        className="w-full object-cover max-h-[600px] rounded-2xl"
        data-slice-type={slice.slice_type}
        data-slice-variation={slice.variation}>
        <Image
          width={0}
          height={0}
          sizes="100vw"
          loading="lazy"
          className="w-full object-cover max-h-[600px] rounded-2xl"
          src={slice.primary.blogMainImage.url || ""}
          alt={slice.primary.blogMainImage.alt || "blogMainImage"}
        />
      </section>
    </Fragment>
  );
};

export default BlogImage;

// src/lib/slices/BlogImage/index.svelte
<script lang="ts">
	import type { Content } from "@prismicio/client";
	import type { SliceComponentProps } from "@prismicio/svelte";
	import CopyLinkButton from "$lib/components/Basic/CopyLinkButton/CopyLinkButton.svelte";
	import CmsImage from "$lib/components/Basic/Image/CmsImage.svelte";
	import type { BlogContext } from "$lib/server/blog";
	import { formatDate } from "$lib/utils";

	type Props = SliceComponentProps<Content.BlogImageSlice, BlogContext>;

	let { slice, context }: Props = $props();
</script>

<div
	class="blogImage flex items-center justify-between gap-2 max-medium:grid max-medium:grid-cols-2"
>
	<div class="blogImageTags flex flex-wrap items-center gap-1">
		{#each context?.tags ?? [] as tag (tag)}
			<span class="mr-2 rounded-full bg-green/30 px-2 py-1 text-xs font-medium">
				{tag}
			</span>
		{/each}
	</div>
	<span class="blogImageDate text-sm text-gray-500 max-medium:text-base">
		{slice.primary.creationdate ? formatDate(slice.primary.creationdate) : ""}
	</span>
	<CopyLinkButton />
</div>
<section
	class="max-h-[600px] w-full rounded-2xl object-cover"
	data-slice-type={slice.slice_type}
	data-slice-variation={slice.variation}
>
	<CmsImage
		field={slice.primary.blogMainImage}
		fallbackAlt="blogMainImage"
		class="max-h-[600px] w-full rounded-2xl object-cover"
	/>
</section>
