// src/slices/BlogAuthor/index.tsx
import { FC } from "react";
import { Content } from "@prismicio/client";
import { SliceComponentProps, SliceZone } from "@prismicio/react";
import { createClient } from "@/prismicio";
import { notFound } from "next/navigation";
import { components } from "..";

/**
 * Props for `BlogAuthor`.
 */
export type BlogAuthorProps = SliceComponentProps<Content.BlogAuthorSlice>;

/**
 * Component for "BlogAuthor" Slices.
 */
const BlogAuthor: FC<BlogAuthorProps> = async ({ slice }) => {
  const client = createClient();
  const blogauthor = slice.primary.blogauthor;

  if (
    !blogauthor ||
    blogauthor.link_type !== "Document" ||
    typeof blogauthor.uid !== "string"
  ) {
    notFound();
  }

  try {
    const author = await client.getByUID("author", blogauthor.uid);
    return (
      <section
        data-slice-type={slice.slice_type}
        data-slice-variation={slice.variation}
        className="max-w-3xl mx-auto flex items-center justify-start gap-10">
        <SliceZone
          context={author}
          slices={author.data.slices}
          components={components}
        />
      </section>
    );
  } catch (error) {
    notFound();
  }
};

export default BlogAuthor;

// src/lib/slices/BlogAuthor/index.svelte
<!--
  The author document is resolved in the page `load` (getBlogPost) and passed
  in `context`. Next fetched it inside the slice and turned a broken author
  link into a 404 for the whole post. Here the section is skipped instead.
  The slice simulator passes no context, so it gets a labelled placeholder.
-->
<script lang="ts">
	import type { Content } from "@prismicio/client";
	import { SliceZone, type SliceComponentProps } from "@prismicio/svelte";
	import type { BlogContext } from "$lib/server/blog";
	import { components } from "..";

	type Props = SliceComponentProps<Content.BlogAuthorSlice, BlogContext>;

	let { slice, context }: Props = $props();

	const link = $derived(slice.primary.blogauthor);
</script>

{#if context?.author}
	<section
		data-slice-type={slice.slice_type}
		data-slice-variation={slice.variation}
		class="mx-auto flex max-w-3xl items-center justify-start gap-10"
	>
		<SliceZone
			slices={context.author.data.slices}
			{components}
			context={context.author}
		/>
	</section>
{:else if !context || !("author" in context)}
	<section
		data-slice-type={slice.slice_type}
		data-slice-variation={slice.variation}
		class="mx-auto max-w-3xl rounded border border-dashed p-4 text-sm"
	>
		Autor: {"uid" in link && link.uid ? link.uid : "(verknüpftes Dokument)"}
	</section>
{/if}
