// web/src/lib/components/Footer/Footer.svelte
<script lang="ts">
	import Image from "$lib/components/Basic/Image/Image.svelte";
	import {
		footer_logo,
		insta,
		linkedin,
		vdiv_footer_new,
		xIcon,
		youtube,
	} from "$lib/assets/icons";
	import type { FooterLinkGroupType } from "$lib/types";
	import FooterEmailForm from "./FooterEmailForm.svelte";
	import FooterLink from "./FooterLink.svelte";
	import {
		DienstleistungenLinksGroup,
		datenschutzLinksGroup,
		gerateLinksGroup,
		kundenLinksGroup,
		newsInfoLinksGroup,
		rechtlichesLinksGroup,
		standorteLinksGroup,
	} from "./footerLinks";

	const socials = [
		{
			href: "https://www.youtube.com/channel/UCv0HIBEJGgD_vNRIkNg6--Q",
			icon: youtube,
			alt: "youtube",
		},
		{ href: "https://x.com/Heidisystems", icon: xIcon, alt: "x" },
		{
			href: "https://www.linkedin.com/company/heidisystems/",
			icon: linkedin,
			alt: "linkedin",
		},
		{
			href: "https://www.instagram.com/heidisystems/",
			icon: insta,
			alt: "insta",
		},
	];
</script>

{#snippet linkGroup(group: FooterLinkGroupType)}
	<div class="space-y-2.5">
		<a
			class="mb-3.5 inline-block text-lg leading-[21px] font-bold text-dark_text"
			href={group.mainUrl}
		>
			{group.title}
		</a>
		{#each group.groupLinks as link (link.text)}
			<FooterLink {link} />
		{/each}
	</div>
{/snippet}

<footer
	class="bg-card_dark_bg px-[72px] pt-16 pb-12 max-megalarge:px-6 max-medium:px-5"
>
	<div class="border-b border-dark_green/10 pb-16">
		<div
			class="mt-6 grid grid-cols-5 gap-10 max-megalarge:gap-4 max-large:flex max-large:flex-wrap max-large:items-start max-large:justify-between"
		>
			<div class="space-y-9">
				{@render linkGroup(gerateLinksGroup)}
				{@render linkGroup(DienstleistungenLinksGroup)}
			</div>
			{@render linkGroup(standorteLinksGroup)}
			{@render linkGroup(rechtlichesLinksGroup)}
			<div class="flex flex-col justify-between space-y-9">
				{@render linkGroup(kundenLinksGroup)}
				{@render linkGroup(datenschutzLinksGroup)}
			</div>
			<div class="flex flex-col justify-between">
				{@render linkGroup(newsInfoLinksGroup)}
				<div class="flex flex-col items-start justify-center">
					<a
						target="_blank"
						href="https://vdiv.de/partneruebersicht/heidi-systems"
					>
						<p class="text-xs text-dark_text">Kooperationspartner:</p>
						<Image
							width={0}
							height={0}
							sizes="100vw"
							class="mb-2 block max-h-[92px] max-w-[150px]"
							src={vdiv_footer_new}
							alt="footer logo"
						/>
					</a>
				</div>
			</div>
		</div>
	</div>
	<div
		class="flex items-center justify-between border-b border-dark_green/10 py-8 max-megalarge:flex-wrap max-megalarge:justify-start max-megalarge:gap-4"
	>
		<div class="max-medium:hidden">
			<Image
				width={0}
				height={0}
				sizes="100vw"
				class="mb-2 block"
				src={footer_logo}
				alt="footer logo"
			/>
			<p class="max-w-[180px] text-lg leading-[21px] text-dark_text/50">
				Heidi Systems GmbH Monbijoupl. 4 <br /> 10178 Berlin
			</p>
		</div>
		<div
			class="max-w-lg text-[30px] leading-9 text-dark_text max-large:max-w-full max-medium:text-[19px] max-medium:leading-[22px] max-small:px-2 max-small:text-base max-small:leading-5"
		>
			Werde Teil der Revolution: Schon mehr als 15.000+ Geräte erfolgreich
			installiert.
		</div>
		<FooterEmailForm />
	</div>
	<div
		class="flex items-start justify-between pt-8 max-large:flex-wrap max-large:justify-start max-large:gap-3 max-medium:flex-col-reverse max-medium:items-center max-medium:gap-8"
	>
		<p class="max-w-4xl text-xs leading-[14px] text-dark_text">
			Die Heidi Systems GmbH erbringt Messdienstleistungen sowie digitale
			Verbrauchserfassungs- und Abrechnungslösungen nach Maßgabe der jeweils
			geltenden gesetzlichen Bestimmungen. Alle auf dieser Website
			bereitgestellten Inhalte dienen ausschließlich der allgemeinen Information
			und begründen weder einen Rechtsanspruch noch eine Verpflichtung. Trotz
			sorgfältiger Prüfung wird keine Haftung für die Richtigkeit,
			Vollständigkeit oder Aktualität der dargestellten Informationen
			übernommen. Haftungsansprüche gegen die Heidi Systems GmbH aufgrund von
			materiellen oder immateriellen Schäden sind – soweit gesetzlich zulässig –
			ausgeschlossen. Sämtliche auf dieser Website verwendeten Texte, Marken,
			Darstellungen und technischen Inhalte unterliegen dem Urheberrecht und
			dürfen nur mit schriftlicher Zustimmung verwendet werden. Verbindliche
			Aussagen zu Leistungen, Preisen oder technischen Spezifikationen erfolgen
			ausschließlich im Rahmen eines individuellen Vertragsverhältnisses.
		</p>
		<div class="flex items-center justify-end gap-3">
			{#each socials as social (social.alt)}
				<a href={social.href}>
					<Image
						width={20}
						height={20}
						sizes="100vw"
						src={social.icon}
						alt={social.alt}
					/>
				</a>
			{/each}
		</div>
	</div>
</footer>

// src/components/Footer/Footer.tsx
import {
  ROUTE_DATENSCHUTZHINWEISE,
  ROUTE_FUNKTIONEN,
  ROUTE_GERAETE,
  ROUTE_IMPRESSUM,
  ROUTE_BLOG,
  ROUTE_HOME,
} from "@/routes/routes";
import {
  footer_logo,
  insta,
  linkedin,
  xIcon,
  youtube,
  vdiv_footer,
} from "@/static/icons";
import Image from "next/image";
import Link from "next/link";
import FooterLink from "./FooterLink";
import type { FooterLinkGroupType } from "@/types";
import FooterEmailForm from "./FooterEmailForm";

export const gerateLinksGroup: FooterLinkGroupType = {
  title: "Geräte",
  mainUrl: ROUTE_GERAETE,
  groupLinks: [
    {
      url: ROUTE_GERAETE,
      text: "Kaltwasser",
      isNeu: false,
    },
    {
      url: ROUTE_GERAETE,
      text: "Warmwasser",
      isNeu: false,
    },
    {
      url: ROUTE_GERAETE,
      text: "Heizung",
      isNeu: false,
    },
    {
      url: ROUTE_GERAETE,
      text: "Rauchmelder",
      isNeu: false,
    },
    {
      url: ROUTE_GERAETE,
      text: "Gas",
      isNeu: false,
    },
  ],
};

export const DienstleistungenLinksGroup: FooterLinkGroupType = {
  title: "Dienstleistungenen",
  mainUrl: ROUTE_FUNKTIONEN,
  groupLinks: [
    {
      url: ROUTE_FUNKTIONEN,
      text: "Unterjährige Verbrauchserfassung",
      isNeu: false,
    },
    {
      url: ROUTE_FUNKTIONEN,
      text: "Heizkostenabrechnung",
      isNeu: false,
    },
    {
      url: ROUTE_FUNKTIONEN,
      text: "Verbrauchsinformation",
      isNeu: false,
    },
    {
      url: ROUTE_FUNKTIONEN,
      text: "Energieausweis",
      isNeu: false,
    },
    {
      url: ROUTE_FUNKTIONEN,
      text: "Großprojekte",
      isNeu: false,
    },
  ],
};

export const standorteLinksGroup: FooterLinkGroupType = {
  title: "Standorte",
  mainUrl: ROUTE_FUNKTIONEN,
  groupLinks: [
    {
      url: ROUTE_FUNKTIONEN,
      text: "Berlin",
      isNeu: false,
    },
    {
      url: ROUTE_FUNKTIONEN,
      text: "Hamburg",
      isNeu: false,
    },
    {
      url: ROUTE_FUNKTIONEN,
      text: "München",
      isNeu: false,
    },
    {
      url: ROUTE_FUNKTIONEN,
      text: "Frankfurt",
      isNeu: false,
    },
    {
      url: ROUTE_FUNKTIONEN,
      text: "Leipzig",
      isNeu: true,
    },
    {
      url: ROUTE_FUNKTIONEN,
      text: "Stuttgart",
      isNeu: false,
    },
    {
      url: ROUTE_FUNKTIONEN,
      text: "Hannover",
      isNeu: false,
    },
    {
      url: ROUTE_FUNKTIONEN,
      text: "Bielefeld",
      isNeu: false,
    },
    {
      url: ROUTE_FUNKTIONEN,
      text: "Wolfsburg",
      isNeu: true,
    },
    {
      url: ROUTE_FUNKTIONEN,
      text: "Gera",
      isBeliebt: true,
    },
    {
      url: ROUTE_FUNKTIONEN,
      text: "Köln",
      isNeu: false,
    },
    {
      url: ROUTE_FUNKTIONEN,
      text: "Ihre Stadt",
      isNeu: false,
    },
  ],
};

export const rechtlichesLinksGroup: FooterLinkGroupType = {
  title: "Rechtliches",
  mainUrl: ROUTE_BLOG,
  groupLinks: [
    {
      url: ROUTE_BLOG,
      text: "Die Neuerung",
      isNeu: true,
    },
    {
      url: ROUTE_BLOG,
      text: "Rohrwärme (VDI 2077)",
      isNeu: false,
    },
    {
      url: ROUTE_BLOG,
      text: "Rauchmelderpflicht",
      isNeu: false,
    },
    {
      url: ROUTE_BLOG,
      text: "Mess- und Eichverordnung",
      isNeu: false,
    },
    {
      url: ROUTE_BLOG,
      text: "Der CO2- Kostenrechner",
      isNeu: false,
    },
    {
      url: ROUTE_BLOG,
      text: "BAFA Förderantrag",
      isNeu: false,
    },
    {
      url: ROUTE_BLOG,
      text: "Kostenaufteilungsrechner",
      isNeu: false,
    },
    {
      url: ROUTE_BLOG,
      text: "Heizkostenverordnung",
      isNeu: false,
    },
    {
      url: ROUTE_BLOG,
      text: "Funkmesserpflicht",
      isNeu: false,
    },
    {
      url: ROUTE_BLOG,
      text: "Eichverordnung",
      isNeu: false,
    },
    {
      url: ROUTE_BLOG,
      text: "Energieausweis",
      isNeu: false,
    },
  ],
};

export const kundenLinksGroup: FooterLinkGroupType = {
  title: "Kunden",
  mainUrl: ROUTE_HOME,
  groupLinks: [
    {
      url: ROUTE_HOME,
      text: "Hausverwaltungen",
      isNeu: false,
    },
    {
      url: ROUTE_HOME,
      text: "Private Equity",
      isNeu: false,
    },
    {
      url: ROUTE_HOME,
      text: "Wohnungsgesellschaften",
      isNeu: false,
    },
    {
      url: ROUTE_HOME,
      text: "Hauseigentümer",
      isNeu: false,
    },
  ],
};

export const datenschutzLinksGroup: FooterLinkGroupType = {
  title: "Datenschutz",
  mainUrl: ROUTE_DATENSCHUTZHINWEISE,
  groupLinks: [
    {
      url: ROUTE_DATENSCHUTZHINWEISE,
      text: "AGB",
      isNeu: false,
    },
    {
      url: ROUTE_IMPRESSUM,
      text: "Impressum",
      isNeu: false,
    },
    {
      url: ROUTE_DATENSCHUTZHINWEISE,
      text: "Datenschutz",
      isNeu: false,
    },
  ],
};

export const newsInfoLinksGroup: FooterLinkGroupType = {
  title: "News & Info",
  mainUrl: ROUTE_BLOG,
  groupLinks: [
    {
      url: ROUTE_BLOG,
      text: "Blog",
      isBeliebt: true,
    },
    {
      url: ROUTE_BLOG,
      text: "Newsletter",
      isNeu: false,
    },
    {
      url: ROUTE_BLOG,
      text: "Webinare",
      isNeu: false,
    },
    {
      url: ROUTE_BLOG,
      text: "Vororttermin",
      isNeu: true,
    },
    {
      url: ROUTE_BLOG,
      text: "Downloads",
      isNeu: false,
    },
    {
      url: ROUTE_BLOG,
      text: "FAQ",
      isNeu: false,
    },
  ],
};

export default function Footer() {
  return (
    <footer className="px-[72px] max-megalarge:px-6 max-medium:px-5 bg-card_dark_bg pt-16 pb-12">
      {/*<div className="flex items-center justify-between gap-5 max-large:flex-wrap max-large:gap-3">
        {simpleFooterLinks.map((link) => (
          <Link
            className="text-lg leading-[21px] font-bold text-dark_text"
            href={link.url}
            key={link.text}
          >
            {link.text}
          </Link>
        ))}
      </div>*/}
      <div className="border-b border-dark_green/10 pb-16">
        <div className="mt-6 grid grid-cols-5 gap-10 max-megalarge:gap-4 max-large:flex max-large:items-start max-large:justify-between max-large:flex-wrap">
          <div className="space-y-9">
            <div className="space-y-2.5">
              <Link
                className="text-lg leading-[21px] mb-3.5 font-bold text-dark_text inline-block"
                href={gerateLinksGroup.mainUrl}
              >
                {gerateLinksGroup.title}
              </Link>
              {gerateLinksGroup.groupLinks.map((link) => (
                <FooterLink key={link.text} link={link} />
              ))}
            </div>
            <div className="space-y-2.5">
              <Link
                className="text-lg leading-[21px] mb-3.5 font-bold text-dark_text inline-block"
                href={DienstleistungenLinksGroup.mainUrl}
              >
                {DienstleistungenLinksGroup.title}
              </Link>
              {DienstleistungenLinksGroup.groupLinks.map((link) => (
                <FooterLink key={link.text} link={link} />
              ))}
            </div>
          </div>
          <div className="space-y-2.5">
            <Link
              className="text-lg leading-[21px] mb-3.5 font-bold text-dark_text inline-block"
              href={standorteLinksGroup.mainUrl}
            >
              {standorteLinksGroup.title}
            </Link>
            {standorteLinksGroup.groupLinks.map((link) => (
              <FooterLink key={link.text} link={link} />
            ))}
          </div>
          <div className="space-y-2.5">
            <Link
              className="text-lg leading-[21px] mb-3.5 font-bold text-dark_text inline-block"
              href={rechtlichesLinksGroup.mainUrl}
            >
              {rechtlichesLinksGroup.title}
            </Link>
            {rechtlichesLinksGroup.groupLinks.map((link) => (
              <FooterLink key={link.text} link={link} />
            ))}
          </div>
          <div className="space-y-9 flex flex-col justify-between">
            <div className="space-y-2.5">
              <Link
                className="text-lg leading-[21px] mb-3.5 font-bold text-dark_text inline-block"
                href={kundenLinksGroup.mainUrl}
              >
                {kundenLinksGroup.title}
              </Link>
              {kundenLinksGroup.groupLinks.map((link) => (
                <FooterLink key={link.text} link={link} />
              ))}
            </div>
            <div className="space-y-2.5">
              <Link
                className="text-lg leading-[21px] mb-3.5 font-bold text-dark_text inline-block"
                href={datenschutzLinksGroup.mainUrl}
              >
                {datenschutzLinksGroup.title}
              </Link>
              {datenschutzLinksGroup.groupLinks.map((link) => (
                <FooterLink key={link.text} link={link} />
              ))}
            </div>
          </div>
          <div className="flex flex-col justify-between">
            <div className="space-y-2.5">
              <Link
                className="text-lg leading-[21px] mb-3.5 font-bold text-dark_text inline-block"
                href={newsInfoLinksGroup.mainUrl}
              >
                {newsInfoLinksGroup.title}
              </Link>
              {newsInfoLinksGroup.groupLinks.map((link) => (
                <FooterLink key={link.text} link={link} />
              ))}
            </div>
            <div className="flex items-start justify-center flex-col">
              <Link
                target="_blank"
                href="https://vdiv.de/partneruebersicht/heidi-systems"
              >
                <p className="text-xs text-dark_text">Kooperationspartner:</p>
                <Image
                  width={0}
                  height={0}
                  sizes="100vw"
                  loading="lazy"
                  className="block mb-2 max-h-[92px] max-w-[150px]"
                  src={vdiv_footer}
                  alt="footer logo"
                />
              </Link>
            </div>
          </div>
        </div>
      </div>
      <div className="border-b border-dark_green/10 py-8 flex items-center justify-between max-megalarge:gap-4 max-megalarge:flex-wrap max-megalarge:justify-start">
        <div className="max-medium:hidden">
          <Image
            width={0}
            height={0}
            sizes="100vw"
            loading="lazy"
            className="block mb-2"
            src={footer_logo}
            alt="footer logo"
          />
          <p className="max-w-[180px] text-dark_text/50 text-lg leading-[21px]">
            Heidi Systems GmbH Rungestrasse 21 10179 Berlin
          </p>
        </div>
        <div className="text-dark_text text-[30px] leading-9 max-w-lg max-medium:text-[19px] max-medium:leading-[22px] max-small:text-base max-small:leading-5 max-small:px-2 max-large:max-w-full">
          Werde Teil der Revolution: Schon mehr als 15.000+ Geräte erfolgreich
          installiert.
        </div>
        <FooterEmailForm />
      </div>
      <div className="pt-8 flex items-start justify-between max-large:flex-wrap max-medium:flex-col-reverse max-medium:items-center max-large:justify-start max-large:gap-3 max-medium:gap-8">
        <p className="text-dark_text text-xs leading-[14px] max-w-4xl">
          Die Heidi Systems GmbH erbringt Messdienstleistungen sowie digitale
          Verbrauchserfassungs- und Abrechnungslösungen nach Maßgabe der jeweils
          geltenden gesetzlichen Bestimmungen. Alle auf dieser Website
          bereitgestellten Inhalte dienen ausschließlich der allgemeinen
          Information und begründen weder einen Rechtsanspruch noch eine
          Verpflichtung. Trotz sorgfältiger Prüfung wird keine Haftung für die
          Richtigkeit, Vollständigkeit oder Aktualität der dargestellten
          Informationen übernommen. Haftungsansprüche gegen die Heidi Systems
          GmbH aufgrund von materiellen oder immateriellen Schäden sind – soweit
          gesetzlich zulässig – ausgeschlossen. Sämtliche auf dieser Website
          verwendeten Texte, Marken, Darstellungen und technischen Inhalte
          unterliegen dem Urheberrecht und dürfen nur mit schriftlicher
          Zustimmung verwendet werden. Verbindliche Aussagen zu Leistungen,
          Preisen oder technischen Spezifikationen erfolgen ausschließlich im
          Rahmen eines individuellen Vertragsverhältnisses.
        </p>
        <div className="flex items-center justify-end gap-3">
          <Link href="https://www.youtube.com/channel/UCv0HIBEJGgD_vNRIkNg6--Q">
            <Image
              width={20}
              height={20}
              sizes="100vw"
              loading="lazy"
              src={youtube}
              alt="youtube"
            />
          </Link>
          <Link href="https://x.com/Heidisystems">
            <Image
              width={20}
              height={20}
              sizes="100vw"
              loading="lazy"
              src={xIcon}
              alt="x"
            />
          </Link>
          <Link href="https://www.linkedin.com/company/heidisystems/">
            <Image
              width={20}
              height={20}
              sizes="100vw"
              loading="lazy"
              src={linkedin}
              alt="linkedin"
            />
          </Link>
          <Link href="https://www.instagram.com/heidisystems/">
            <Image
              width={20}
              height={20}
              sizes="100vw"
              loading="lazy"
              src={insta}
              alt="insta"
            />
          </Link>
        </div>
      </div>
    </footer>
  );
}
