// src/components/Kontakt/ContactForm.tsx
"use client";

import { useForm } from "react-hook-form";
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import { useMutation } from "@tanstack/react-query";
import { useState, useRef, useEffect } from "react";

const formSchema = z.object({
  name: z.string().min(3, "Name muss mindestens 3 Zeichen lang sein"),
  email: z.string().email("Bitte eine gültige E-Mail-Adresse eingeben"),
  message: z.string().min(10, "Nachricht muss mindestens 10 Zeichen enthalten"),
  infoChecked: z.literal(true, {
    errorMap: () => ({
      message: "Bitte akzeptieren Sie die Datenschutzbestimmungen",
    }),
  }),
  // Honeypot field — invisible to real users, bots auto-fill it
  website: z.string().max(0).optional(),
});

type FormData = z.infer<typeof formSchema>;

export default function ContactForm() {
  const {
    register,
    handleSubmit,
    formState: { errors },
    reset,
  } = useForm({
    resolver: zodResolver(formSchema),
  });
  const [formMessage, setFormMessage] = useState({ text: "", type: "" });
  const formLoadedAt = useRef<number>(Date.now());

  useEffect(() => {
    formLoadedAt.current = Date.now();
  }, []);

  const mutation = useMutation({
    mutationFn: async (data: FormData) => {
      const { website, ...formFields } = data;
      const response = await fetch("/api/contact", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          ...formFields,
          _hp: website || "",
          _t: formLoadedAt.current,
        }),
      });

      if (!response.ok) {
        setFormMessage({
          text: "Fehler beim Senden der Nachricht. Bitte versuchen Sie es erneut.",
          type: "error",
        });
        throw new Error("Fehler beim Senden der Nachricht");
      }

      setFormMessage({
        text: "Ihre Nachricht wurde erfolgreich gesendet!",
        type: "success",
      });
      reset();
      return response.json();
    },
  });
  return (
    <div className="pt-20 max-small:pt-8 px-[100px] max-large:px-20 max-medium:px-10 max-small:px-5">
      <h1 className="text-[45px] leading-[54px] mb-6 max-medium:text-2xl text-dark_text">
        Kontaktieren Sie uns
      </h1>
      <p className="text-lg text-dark_text mb-5">
        Unser Service Team bearbeitet Anfragen überlich innerhalb von 24 Stunden
        per Email.
      </p>
      {formMessage.text && (
        <p
          role="alert"
          className={`mb-4 text-sm font-semibold ${
            formMessage.type === "success" ? "text-green-500" : "text-red-500"
          }`}
        >
          {formMessage.text}
        </p>
      )}
      <form
        onSubmit={handleSubmit((data) => mutation.mutate(data))}
        id="contactForm"
        className="space-y-4"
      >
        {/* Honeypot — hidden from real users, bots auto-fill this */}
        <div aria-hidden="true" className="absolute opacity-0 -z-10 h-0 w-0 overflow-hidden pointer-events-none" style={{ position: "absolute", left: "-9999px" }}>
          <label>
            Website
            <input
              {...register("website")}
              tabIndex={-1}
              autoComplete="off"
              type="text"
            />
          </label>
        </div>

        <label className="block">
          <input
            {...register("name")}
            className="w-full border border-dark_green/20 rounded-md py-5 px-7 duration-300 outline-none focus:ring-4 focus:ring-green/40"
            placeholder="Vor- und Nachname*"
            type="text"
          />
          {errors.name && (
            <p className="text-red-500 text-sm">{errors.name.message}</p>
          )}
        </label>
        <label className="block">
          <input
            {...register("email")}
            className="w-full border border-dark_green/20 rounded-md py-5 px-7 duration-300 outline-none focus:ring-4 focus:ring-green/40"
            placeholder="E-Mail*"
            type="email"
          />
          {errors.email && (
            <p className="text-red-500 text-sm">{errors.email.message}</p>
          )}
        </label>
        <label className="block">
          <textarea
            {...register("message")}
            className="w-full border border-dark_green/20 rounded-md py-5 px-7 duration-300 outline-none focus:ring-4 focus:ring-green/40"
            placeholder="Nachricht*"
          ></textarea>
          {errors.message && (
            <p className="text-red-500 text-sm">{errors.message.message}</p>
          )}
        </label>
        <div className="flex items-center justify-start gap-7">
          <input
            {...register("infoChecked")}
            type="checkbox"
            className="accent-green size-[18px]"
          />
          <label htmlFor="infoChecked">
            Hiermit habe ich die{" "}
            <a href="#" className="text-green-600 underline">
              Datenschutzbestimmungen
            </a>{" "}
            gelesen und akzeptiert.
          </label>
        </div>
        {errors.infoChecked && (
          <p className="text-red-500 text-sm">{errors.infoChecked.message}</p>
        )}

        <button
          className="py-4 px-9 text-[15px] cursor-pointer duration-300 hover:opacity-80 font-bold text-white rounded-md bg-green disabled:opacity-50"
          type="submit"
          disabled={mutation.isPending}
        >
          {mutation.isPending ? "Senden..." : "Bestätigen"}
        </button>
      </form>
    </div>
  );
}

// src/lib/components/Kontakt/ContactForm.svelte
<!-- Posts to the /kontakt form action; works without JS. -->
<script lang="ts">
	import { onMount, untrack } from "svelte";
	import { superForm, type SuperValidated } from "sveltekit-superforms";
	import { zod4Client } from "sveltekit-superforms/adapters";
	import { contactFormSchema } from "$lib/forms/contact";
	import { ROUTE_DATENSCHUTZHINWEISE } from "$lib/routes";
	import type { z } from "zod";

	type Props = {
		data: SuperValidated<z.infer<typeof contactFormSchema>>;
	};

	let { data }: Props = $props();

	const { form, errors, enhance, message, submitting } = superForm(
		// superForm takes the initial form once and tracks updates itself
		untrack(() => data),
		{
			validators: zod4Client(contactFormSchema),
		},
	);

	// The server's render time can be minutes old when the CDN serves this
	// page, so time from hydration, as Next did.
	onMount(() => {
		$form._t = Date.now();
	});
</script>

<div
	class="px-[100px] pt-20 max-large:px-20 max-medium:px-10 max-small:px-5 max-small:pt-8"
>
	<h1
		class="mb-6 text-[45px] leading-[54px] text-dark_text max-medium:text-2xl"
	>
		Kontaktieren Sie uns
	</h1>
	<p class="mb-5 text-lg text-dark_text">
		Unser Service Team bearbeitet Anfragen überlich innerhalb von 24 Stunden per
		Email.
	</p>
	{#if $message}
		<p
			role="alert"
			class={[
				"mb-4 text-sm font-semibold",
				$message.type === "success" ? "text-green-500" : "text-red-500",
			]}
		>
			{$message.text}
		</p>
	{/if}
	<form method="POST" use:enhance id="contactForm" class="space-y-4">
		<input type="hidden" name="_t" value={$form._t} />
		<!-- Honeypot — hidden from real users, bots auto-fill this -->
		<div
			aria-hidden="true"
			class="pointer-events-none absolute -left-[9999px] -z-10 h-0 w-0 overflow-hidden opacity-0"
		>
			<label>
				Website
				<input
					name="website"
					bind:value={$form.website}
					tabindex={-1}
					autocomplete="off"
					type="text"
				/>
			</label>
		</div>

		<label class="block">
			<input
				name="name"
				bind:value={$form.name}
				class="w-full rounded-md border border-dark_green/20 px-7 py-5 duration-300 outline-none focus:ring-4 focus:ring-green/40"
				placeholder="Vor- und Nachname*"
				type="text"
			/>
			{#if $errors.name}
				<p class="text-sm text-red-500">{$errors.name[0]}</p>
			{/if}
		</label>
		<label class="block">
			<input
				name="email"
				bind:value={$form.email}
				class="w-full rounded-md border border-dark_green/20 px-7 py-5 duration-300 outline-none focus:ring-4 focus:ring-green/40"
				placeholder="E-Mail*"
				type="email"
			/>
			{#if $errors.email}
				<p class="text-sm text-red-500">{$errors.email[0]}</p>
			{/if}
		</label>
		<label class="block">
			<textarea
				name="message"
				bind:value={$form.message}
				class="w-full rounded-md border border-dark_green/20 px-7 py-5 duration-300 outline-none focus:ring-4 focus:ring-green/40"
				placeholder="Nachricht*"></textarea>
			{#if $errors.message}
				<p class="text-sm text-red-500">{$errors.message[0]}</p>
			{/if}
		</label>
		<div class="flex items-center justify-start gap-7">
			<input
				id="infoChecked"
				name="infoChecked"
				bind:checked={$form.infoChecked}
				type="checkbox"
				class="size-[18px] accent-green"
			/>
			<label for="infoChecked">
				Hiermit habe ich die
				<a href={ROUTE_DATENSCHUTZHINWEISE} class="text-green-600 underline"
					>Datenschutzbestimmungen</a
				>
				gelesen und akzeptiert.
			</label>
		</div>
		{#if $errors.infoChecked}
			<p class="text-sm text-red-500">{$errors.infoChecked[0]}</p>
		{/if}

		<button
			class="cursor-pointer rounded-md bg-green px-9 py-4 text-[15px] font-bold text-white duration-300 hover:opacity-80 disabled:opacity-50"
			type="submit"
			disabled={$submitting}
		>
			{$submitting ? "Senden..." : "Bestätigen"}
		</button>
	</form>
</div>
