// src/app/(base)/blog/page.tsx
import Subscription from "@/components/Basic/Subscription/Subscription";
import BlogFilters from "@/components/Blog/BlogFilters";
import NewestBlogs from "@/components/Blog/NewestBlogs";
import BlogHero from "@/components/Hero/BlogHero";

export default async function BlogPage() {
  return (
    <main id="content">
      <BlogHero />
      <NewestBlogs />
      <BlogFilters />
      <div className="bg-[#FAFAF9] flex items-center gap-32 justify-center py-8 pl-5 px-4">
        <div className="flex flex-col items-center justify-center gap-4">
          <p className="text-center font-semibold max-w-6xl mx-auto leading-[1.1] text-7xl max-megalarge:text-6xl max-large:text-5xl max-medium:text-4xl max-small:text-3xl">
            Melde dich für unseren Newsletter für Werbetreibende an.
          </p>
          <p className="text-lg max-large:text-base text-center font-semibold">
            Du wirst als Erstes über Unternehmensneuigkeiten, Events und
            Insights informiert.
          </p>
        </div>
      </div>
      <Subscription />
    </main>
  );
}

// src/routes/[[preview=preview]]/(base)/blog/+page.svelte
<script lang="ts">
	import Subscription from "$lib/components/Basic/Subscription/Subscription.svelte";
	import BlogFilters from "$lib/components/Blog/BlogFilters.svelte";
	import NewestBlogs from "$lib/components/Blog/NewestBlogs.svelte";
	import BlogHero from "$lib/components/Hero/BlogHero.svelte";

	let { data } = $props();
</script>

<main id="content">
	<BlogHero />
	<NewestBlogs posts={data.newest} />
	<BlogFilters posts={data.posts} tags={data.tags} activeTag={data.activeTag} />
	<div
		class="flex items-center justify-center gap-32 bg-[#FAFAF9] px-4 py-8 pl-5"
	>
		<div class="flex flex-col items-center justify-center gap-4">
			<p
				class="mx-auto max-w-6xl text-center text-7xl leading-[1.1] font-semibold max-megalarge:text-6xl max-large:text-5xl max-medium:text-4xl max-small:text-3xl"
			>
				Melde dich für unseren Newsletter für Werbetreibende an.
			</p>
			<p class="text-center text-lg font-semibold max-large:text-base">
				Du wirst als Erstes über Unternehmensneuigkeiten, Events und Insights
				informiert.
			</p>
		</div>
	</div>
	<Subscription />
</main>
