// src/app/(service)/fragebogen/page.tsx
"use client";

import { LazyLottie } from "@/components/Lottie/LazyLottie";
import { checkmark_icon_big, chevron, counter, info } from "@/static/icons";
import { animation5, animation6 } from "@/static/lottieAnimations";
import Image from "next/image";
import { Fragment, useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import { useMutation } from "@tanstack/react-query";
import StepWrapper from "@/components/Fragebogen/StepWrapper";
import { useQuestionareStore } from "@/store/useQuestionareStore";
import StepInfo from "@/components/Fragebogen/StepInfo";

const formSchema = z.object({
	email: z.string().email("Ungültige E-Mail-Adresse").nullable(),
	first_name: z.string().min(1, "Vorname ist erforderlich").nullable(),
	last_name: z.string().min(1, "Nachname ist erforderlich").nullable(),
	appartment_number: z.number().min(1, "Wohnungsnummer ist erforderlich"),
	heating_costs: z
		.enum([
			"Durch mich persönlich",
			"Durch einen anderen Messdienstleister",
			"Bisher noch gar nicht",
		])
		.refine((val) => !!val, {
			message: "Heizkosten müssen angegeben werden",
		})
		.nullable(),
	heating_available: z
		.enum(["Ja", "Nein"])
		.refine((val) => !!val, {
			message: "Angabe erforderlich",
		})
		.nullable(),
	central_water_supply: z
		.enum(["Ja", "Nein"])
		.refine((val) => !!val, {
			message: "Angabe erforderlich",
		})
		.nullable(),
	central_heating_system: z
		.enum([
			"Nur Heizkörper",
			"Nur Fußbodenheizung",
			"Heizkörper und Fußbodenheizung",
		])
		.refine((val) => !!val, {
			message: "Angabe erforderlich",
		})
		.nullable(),
	energy_sources: z
		.string()
		.min(1, "Energiequelle ist erforderlich")
		.nullable(),
	form_confirm: z.boolean().refine((val) => val === true, {
		message: "Bitte akzeptieren Sie die Datenschutzbestimmungen",
	}),
});

export type QuestionareFormData = z.infer<typeof formSchema>;

export default function FragebogenPage() {
	const {
		activeStep,
		totalSteps,
		handleNextStep,
		handlePrevStep,
		totalStepsNumber,
	} = useQuestionareStore();

	const [isSubmited, setIsSubmited] = useState<boolean>(false);
	const {
		register,
		handleSubmit,
		formState: { errors },
		reset,
		watch,
		setValue,
	} = useForm({
		resolver: zodResolver(formSchema),
		defaultValues: {
			appartment_number: 2,
			email: "",
			first_name: "",
			last_name: "",
			heating_costs: null,
			heating_available: null,
			central_water_supply: null,
			central_heating_system: null,
			energy_sources: "",
			form_confirm: false,
		},
	});

	const mutation = useMutation({
		mutationFn: async (data: QuestionareFormData) => {
			const response = await fetch(
				"https://hook.eu2.make.com/jd0ux1knh1rvreg6jcto9egpfk5gw1s9",
				{
					method: "POST",
					headers: { "Content-Type": "application/json" },
					body: JSON.stringify({
						email: data.email,
						first_name: data.first_name,
						last_name: data.last_name,
						appartment_number: data.appartment_number,
						heating_costs: data.heating_costs,
						heating_available: data.heating_available,
						central_water_supply: data.central_water_supply,
						central_heating_system: data.central_heating_system,
						energy_sources: data.energy_sources,
					}),
				},
			);

			if (!response.ok) {
				throw new Error("Fehler beim Senden der Nachricht");
			}

			return response;
		},
		onSuccess: () => {
			setIsSubmited(true);
			reset();
		},
	});

	return (
		<main id="content" className="pt-8 pb-24 px-5">
			{isSubmited ? (
				<div
					id="questionare-final"
					className="max-w-6xl px-10 max-small:px-5 flex flex-col items-start justify-end mx-auto"
				>
					<Image
						width={0}
						height={0}
						sizes="100vw"
						loading="lazy"
						className="size-[50px] block mb-6"
						src={checkmark_icon_big}
						alt="checkmark"
					/>
					<h1 className="text-[40px] max-small:text-2xl mb-4 text-dark_text">
						Anfrage erfolgreich versendet
					</h1>
					<p className="text-dark_text text-xl max-large:mb-16 max-medium:mb-8 mb-24">
						Wir werden uns in den nächsten 24h bei Ihnen mit einem <br />
						für Sie zugeschnitten Angebot melden.
					</p>
					<div className="grid gap-8 max-medium:grid-cols-1 grid-cols-10">
						<div className="col-span-6 max-medium:col-span-1 space-y-5">
							<p className="bg-dark_green/5 rounded-base text-dark_text text-base py-8 px-6">
								Um eine reibungslose und effiziente Bearbeitung Ihrer Anfrage zu
								gewährleisten, benötigen wir Ihre persönlichen Daten. Diese
								ermöglichen es uns, bei eventuellen Rückfragen direkt mit Ihnen
								in Kontakt zu treten
							</p>
							<div className="grid gap-5 max-medium:grid-cols-1 grid-cols-2">
								<LazyLottie
									animationData={animation5}
									id="questionare-final-animation1"
									wrapperClassName="relative"
								/>

								<LazyLottie
									animationData={animation6}
									id="questionare-final-animation2"
									wrapperClassName="relative"
								/>
							</div>
						</div>
						<div className="col-span-4 max-medium:col-span-1 bg-dark_green/5 rounded-t-base px-10 pt-9">
							<p className="flex items-center text-dark_text justify-start gap-4 text-2xl font-bold mb-14">
								<button>
									<Image
										width={0}
										height={0}
										sizes="100vw"
										loading="lazy"
										src={info}
										alt="info"
									/>
								</button>
								Kostenfreie Installation
							</p>
							<Image
								width={0}
								height={0}
								sizes="100vw"
								loading="lazy"
								className="mx-auto"
								src={counter}
								alt="counter"
							/>
						</div>
					</div>
				</div>
			) : (
				<Fragment>
					<div
						data-filled-steps="0"
						className="steps-progress max-w-6xl mx-auto flex mb-10 items-center justify-start gap-1.5"
					>
						{totalSteps.map((step) => (
							<span
								key={step}
								data-step-index={step}
								className={`w-[50px] h-[1px] ${step <= activeStep ? "bg-green" : "bg-dark_green/10"}`}
							></span>
						))}
						<span className="text-xs text-dark_text/20"> noch 3 min </span>
					</div>
					<div className="questionare-steps max-w-6xl mx-auto flex items-start max-large:flex-col max-large:gap-10 justify-between">
						<form
							onSubmit={handleSubmit((data) => mutation.mutate(data))}
							id="questionare-form"
							className="steps-wrapper"
						>
							{activeStep > 0 && (
								<button
									className="text-[15px] cursor-pointer group text-dark_text/20 font-bold flex items-center justify-start gap-3"
									id="prev-step"
									onClick={() => handlePrevStep()}
									type="button"
								>
									<Image
										width={0}
										height={0}
										sizes="100vw"
										loading="lazy"
										alt="chevron"
										src={chevron}
										className="rotate-180 group-hover:-translate-x-1/2 duration-300 size-2.5 colored-to-black opacity-50"
									/>
									zurück
								</button>
							)}
							{/*  */}
							<StepWrapper
								register={register}
								errors={errors}
								watch={watch}
								setValue={setValue}
								activeStep={activeStep}
							/>
							{/*  */}
							<div className="flex items-center justify-start gap-5">
								<button
									id="next-step"
									className="rounded-base cursor-pointer bg-green flex items-center justify-center duration-300 hover:opacity-80 text-white font-bold text-[15px] disabled:opacity-50 py-4 px-7 border border-transparent"
									onClick={() => handleNextStep()}
									type={`${activeStep === 6 ? "submit" : "button"}`}
								>
									Bestätigen
								</button>
								{activeStep !== totalStepsNumber - 1 && (
									<button
										id="skip-step"
										className="rounded-base cursor-pointer bg-white flex items-center justify-center duration-300 hover:opacity-80 hover:border-green disabled:opacity-50 text-green font-bold text-[15px] py-4 px-7 border border-transparent"
										onClick={() => handleNextStep()}
										type="button"
									>
										Überspringen
									</button>
								)}
							</div>
						</form>
						<StepInfo activeStep={activeStep} />
					</div>
				</Fragment>
			)}
		</main>
	);
}

// web/src/routes/[[preview=preview]]/(service)/fragebogen/+page.svelte
<script lang="ts">
	import { tick } from "svelte";
	import {
		checkmark_icon_big,
		chevron,
		counter,
		info,
	} from "$lib/assets/icons";
	import Image from "$lib/components/Basic/Image/Image.svelte";
	import StepInfo from "$lib/components/Fragebogen/StepInfo.svelte";
	import StepWrapper from "$lib/components/Fragebogen/StepWrapper.svelte";
	import LazyLottie from "$lib/components/Lottie/LazyLottie.svelte";
	import {
		setQuestionnaire,
		type QuestionnaireField,
	} from "$lib/fragebogen/questionnaire.svelte";

	const q = setQuestionnaire();

	/** Focus order for invalid fields, as react-hook-form did on submit. */
	const FOCUS_ORDER: QuestionnaireField[] = [
		"first_name",
		"last_name",
		"phone",
		"email",
		"form_confirm",
	];

	async function onsubmit(e: SubmitEvent) {
		e.preventDefault();
		// Enter in a single text field submits implicitly; only the last step sends
		if (!q.isSubmitStep || q.status === "submitting") return;
		if (await q.submit()) return;
		await tick();
		const invalid = FOCUS_ORDER.find((field) => q.errors[field]);
		if (invalid) document.getElementById(invalid)?.focus();
	}
</script>

<main id="content" class="px-5 pt-8 pb-24">
	{#if q.status === "done"}
		<div
			id="questionare-final"
			class="mx-auto flex max-w-6xl flex-col items-start justify-end px-10 max-small:px-5"
		>
			<Image
				width={0}
				height={0}
				sizes="100vw"
				class="mb-6 block size-[50px]"
				src={checkmark_icon_big}
				alt="checkmark"
			/>
			<h1 class="mb-4 text-[40px] text-dark_text max-small:text-2xl">
				Anfrage erfolgreich versendet
			</h1>
			<p
				class="mb-24 text-xl text-dark_text max-large:mb-16 max-medium:mb-8 max-small:text-base"
			>
				Wir werden uns in den nächsten 24h bei Ihnen mit einem <span
					class="max-small:hidden"><br /></span
				>für Sie zugeschnitten Angebot melden.
			</p>
			<div class="grid grid-cols-10 gap-8 max-medium:grid-cols-1">
				<div class="col-span-6 space-y-5 max-medium:col-span-1">
					<p
						class="rounded-base bg-dark_green/5 px-6 py-8 text-base text-dark_text"
					>
						Um eine reibungslose und effiziente Bearbeitung Ihrer Anfrage zu
						gewährleisten, benötigen wir Ihre persönlichen Daten. Diese
						ermöglichen es uns, bei eventuellen Rückfragen direkt mit Ihnen in
						Kontakt zu treten
					</p>
					<div class="grid grid-cols-2 gap-5 max-medium:grid-cols-1">
						<LazyLottie
							animationName="Animation_5"
							id="questionare-final-animation1"
							wrapperClassName="relative"
						/>
						<LazyLottie
							animationName="Animation_6"
							id="questionare-final-animation2"
							wrapperClassName="relative"
						/>
					</div>
				</div>
				<div
					class="col-span-4 rounded-t-base bg-dark_green/5 px-10 pt-9 max-medium:col-span-1 max-small:px-5"
				>
					<p
						class="mb-14 flex items-center justify-start gap-4 text-2xl font-bold text-dark_text"
					>
						<button>
							<Image width={0} height={0} sizes="100vw" src={info} alt="info" />
						</button>
						Kostenfreie Installation
					</p>
					<Image
						width={0}
						height={0}
						sizes="100vw"
						class="mx-auto"
						src={counter}
						alt="counter"
					/>
				</div>
			</div>
		</div>
	{:else}
		<div
			data-filled-steps="0"
			class="steps-progress mx-auto mb-10 flex max-w-6xl items-center justify-start gap-1.5"
		>
			{#each { length: q.totalSteps }, step (step)}
				<span
					data-step-index={step}
					class={[
						"h-[1px] w-[50px] max-small:w-[30px]",
						step <= q.step ? "bg-green" : "bg-dark_green/10",
					]}
				></span>
			{/each}
			<span class="text-xs text-dark_text/20"> noch 4 min </span>
		</div>
		<div
			class="questionare-steps mx-auto flex max-w-6xl items-start justify-between max-large:flex-col max-large:gap-10 max-small:gap-4"
		>
			<form
				{onsubmit}
				id="questionare-form"
				class="steps-wrapper max-small:order-2"
			>
				{#if q.step > 0}
					<button
						class="group flex cursor-pointer items-center justify-start gap-3 text-[15px] font-bold text-dark_text/20"
						id="prev-step"
						onclick={() => q.prev()}
						type="button"
					>
						<Image
							width={0}
							height={0}
							sizes="100vw"
							alt="chevron"
							src={chevron}
							class="colored-to-black size-2.5 rotate-180 opacity-50 duration-300 group-hover:-translate-x-1/2"
						/>
						zurück
					</button>
				{/if}
				<StepWrapper />
				{#if q.stepError && (q.step === 0 || q.step === 1)}
					<p class="mb-4 text-sm text-red-500">
						Bitte wählen Sie eine Option aus, um fortzufahren.
					</p>
				{/if}
				<div class="flex items-center justify-start gap-5">
					{#if q.isSubmitStep}
						<button
							id="next-step"
							class="flex cursor-pointer items-center justify-center rounded-xl border border-transparent bg-green px-8 py-4 text-[15px] font-bold text-white duration-300 hover:opacity-80 disabled:opacity-50"
							type="submit"
							disabled={q.status === "submitting"}
						>
							{q.status === "submitting" ? "Wird gesendet..." : "Bestätigen"}
						</button>
					{:else}
						<button
							id="next-step"
							class="flex cursor-pointer items-center justify-center rounded-xl border border-transparent bg-green px-8 py-4 text-[15px] font-bold text-white duration-300 hover:opacity-80 disabled:opacity-50"
							type="button"
							onclick={() => q.confirm()}
						>
							Bestätigen
						</button>
					{/if}
					<!-- No skip on step 0 (required) or the last step -->
					{#if q.step !== 0 && !q.isSubmitStep}
						<button
							id="skip-step"
							class="flex cursor-pointer items-center justify-center bg-transparent px-4 py-4 text-[15px] font-bold text-green duration-300 hover:opacity-80 disabled:opacity-50"
							onclick={() => q.next()}
							type="button"
						>
							Überspringen
						</button>
					{/if}
				</div>
			</form>
			<StepInfo activeStep={q.step} />
		</div>
	{/if}
</main>
