// src/components/Hero/HomeHero.tsx
import HeroTicker from "../Basic/Ticker/HeroTicker";
import { LazyLottie } from "@/components/Lottie/LazyLottie";
import Image from "next/image";
import { counter, google, handyman, star } from "@/static/icons";
import Link from "next/link";
import { ROUTE_BLOG, ROUTE_FRAGEBOGEN } from "@/routes/routes";

export default function HomeHero() {
  return (
    <div className="pt-[1px] bg-dark_green">
      <div className="px-4">
        <h1 className="mt-28 max-large:mt-28 max-medium:mt-28 max-small:mt-24 text-white text-[65px] max-medium:text-5xl max-small:text-3xl leading-[78px] max-medium:leading-tight text-center mb-2">
          Fernablesung mit Funkgeräten
        </h1>
        <p className="text-2xl leading-[28px] max-medium:text-base max-small:text-sm max-medium:leading-5 max-medium:text-white/60 text-white text-center max-w-3xl mx-auto my-6">
          Effiziente Fernablesung für Warmwasser, Kaltwasser und Heizung – mit
          fortschrittlicher Funktechnologie
        </p>
        <div className="flex items-center justify-center mx-auto w-fit border border-white/20 rounded-[40px] py-2.5 px-4 max-small:py-2 max-small:px-3 gap-3 max-small:gap-2 mb-10 max-small:mb-6">
          <span className="flex items-center justify-start gap-2 max-small:gap-1">
            <Image
              width={20}
              height={20}
              sizes="(max-width: 480px) 30px, 20px"
              className="max-small:w-[20px] h-auto"
              src={google}
              alt="google"
            />
            <Image
              width={16}
              height={16}
              priority
              sizes="16px"
              className="size-4 max-small:size-3 colored-to-white opacity-80"
              src={star}
              alt="rate star"
            />
            <Image
              width={16}
              height={16}
              priority
              sizes="16px"
              className="size-4 max-small:size-3 colored-to-white opacity-80"
              src={star}
              alt="rate star"
            />
            <Image
              width={16}
              height={16}
              priority
              sizes="16px"
              className="size-4 max-small:size-3 colored-to-white opacity-80"
              src={star}
              alt="rate star"
            />
            <Image
              width={16}
              height={16}
              priority
              sizes="16px"
              className="size-4 max-small:size-3 colored-to-white opacity-80"
              src={star}
              alt="rate star"
            />
            <Image
              width={16}
              height={16}
              priority
              sizes="16px"
              className="size-4 max-small:size-3 colored-to-white opacity-80"
              src={star}
              alt="rate star"
            />
          </span>
          <span className="text-[15px] max-small:text-xs leading-[18px] text-white text-center whitespace-nowrap">
            4.8 Rating
          </span>
          <span className="text-[15px] max-small:text-xs leading-[18px] text-white/70 text-center whitespace-nowrap">
            470 Bewertungen
          </span>
        </div>
        <Link
          href={ROUTE_FRAGEBOGEN}
          className="block text-center mx-auto max-medium:w-full w-fit py-5 max-medium:py-3 px-10 text-lg text-dark_text bg-green rounded-halfbase mb-4"
        >
          Jetzt installieren lassen
        </Link>
        <Link
          href={ROUTE_BLOG}
          className="text-center mx-auto block text-[15px] leading-[18px] text-white"
        >
          Fernablesbare Zähler verpflichtend bis 1. Januar 2027
        </Link>
      </div>
      <div className="px-[72px] mt-[70px] mb-10 max-medium:flex-col w-fit mx-auto max-medium:pr-0 max-medium:justify-end grid grid-cols-4 gap-2 max-medium:px-0">
        <div className="bg-card_bg px-9 rounded-base flex items-center justify-center max-medium:hidden">
          <Image
            width={324}
            height={324}
            priority
            sizes="(max-width: 768px) 0px, 324px"
            src={counter}
            alt="counter"
          />
        </div>
        <LazyLottie
          animationName="Animation_2"
          id="animation2hero"
          wrapperClassName="w-fit col-span-2 max-medium:col-span-4 max-medium:bg-transparent max-medium:ml-auto max-medium:mr-0 bg-card_bg rounded-base max-h-[324px] overflow-hidden"
        />
        <div className="small:w-full max-h-[324px] overflow-hidden rounded-base w-full max-medium:hidden">
          <Image
            width={324}
            height={324}
            priority
            sizes="(max-width: 768px) 0px, 324px"
            className="w-full rounded-base object-contain"
            src={handyman}
            alt="handyman"
          />
        </div>
      </div>
      <HeroTicker />
    </div>
  );
}

// web/src/lib/components/Hero/HomeHero.svelte
<script lang="ts">
	import HeroTicker from "$lib/components/Basic/Ticker/HeroTicker.svelte";
	import Image from "$lib/components/Basic/Image/Image.svelte";
	import LazyLottie from "$lib/components/Lottie/LazyLottie.svelte";
	import { counter, google, handyman, star } from "$lib/assets/icons";
	import { ROUTE_BLOG, ROUTE_FRAGEBOGEN } from "$lib/routes";
</script>

<div class="bg-dark_green pt-[1px]">
	<div class="px-4">
		<h1
			class="mt-28 mb-2 text-center text-[65px] leading-[78px] text-white max-large:mt-28 max-medium:mt-28 max-medium:text-5xl max-medium:leading-tight max-small:mt-24 max-small:text-3xl"
		>
			Fernablesung mit Funkgeräten
		</h1>
		<p
			class="mx-auto my-6 max-w-3xl text-center text-2xl leading-[28px] text-white max-medium:text-base max-medium:leading-5 max-medium:text-white/60 max-small:text-sm"
		>
			Effiziente Fernablesung für Warmwasser, Kaltwasser und Heizung – mit
			fortschrittlicher Funktechnologie
		</p>
		<div
			class="mx-auto mb-10 flex w-fit items-center justify-center gap-3 rounded-[40px] border border-white/20 px-4 py-2.5 max-small:mb-6 max-small:gap-2 max-small:px-3 max-small:py-2"
		>
			<span class="flex items-center justify-start gap-2 max-small:gap-1">
				<Image
					width={20}
					height={20}
					sizes="(max-width: 480px) 30px, 20px"
					class="h-auto max-small:w-[20px]"
					src={google}
					alt="google"
				/>
				{#each { length: 5 }, i (i)}
					<Image
						width={16}
						height={16}
						priority
						sizes="16px"
						class="colored-to-white size-4 opacity-80 max-small:size-3"
						src={star}
						alt="rate star"
					/>
				{/each}
			</span>
			<span
				class="text-center text-[15px] leading-[18px] whitespace-nowrap text-white max-small:text-xs"
			>
				4.8 Rating
			</span>
			<span
				class="text-center text-[15px] leading-[18px] whitespace-nowrap text-white/70 max-small:text-xs"
			>
				470 Bewertungen
			</span>
		</div>
		<a
			href={ROUTE_FRAGEBOGEN}
			class="mx-auto mb-4 block w-fit rounded-halfbase bg-green px-10 py-5 text-center text-lg text-dark_text max-medium:w-full max-medium:py-3"
		>
			Jetzt installieren lassen
		</a>
		<a
			href={ROUTE_BLOG}
			class="mx-auto block text-center text-[15px] leading-[18px] text-white"
		>
			Fernablesbare Zähler verpflichtend bis 1. Januar 2027
		</a>
	</div>
	<div
		class="mx-auto mt-[70px] mb-10 grid w-fit grid-cols-4 gap-2 px-[72px] max-medium:flex-col max-medium:justify-end max-medium:px-0 max-medium:pr-0"
	>
		<div
			class="flex items-center justify-center rounded-base bg-card_bg px-9 max-medium:hidden"
		>
			<Image
				width={324}
				height={324}
				priority
				sizes="(max-width: 768px) 0px, 324px"
				src={counter}
				alt="counter"
			/>
		</div>
		<LazyLottie
			animationName="Animation_2"
			id="animation2hero"
			size={{ w: 1456, h: 1082 }}
			wrapperClassName="w-fit col-span-2 max-medium:col-span-4 max-medium:bg-transparent max-medium:ml-auto max-medium:mr-0 bg-card_bg rounded-base max-h-[324px] overflow-hidden"
		/>
		<div
			class="max-h-[324px] w-full overflow-hidden rounded-base max-medium:hidden small:w-full"
		>
			<Image
				width={324}
				height={324}
				priority
				sizes="(max-width: 768px) 0px, 324px"
				class="w-full rounded-base object-contain"
				src={handyman}
				alt="handyman"
			/>
		</div>
	</div>
	<HeroTicker />
</div>
